name: 3-Tier CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Backend Image
        run: docker build -t $DOCKER_USERNAME/backend-app ./backend

      - name: Push Backend Image
        run: docker push $DOCKER_USERNAME/backend-app


  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Frontend Image
        run: docker build -t $DOCKER_USERNAME/frontend-app ./frontend

      - name: Push Frontend Image
        run: docker push $DOCKER_USERNAME/frontend-app
